version: '3'
services:
  reverse:
    build: .
    depends_on:
      - static
      - app
    ports:
      - "80:80"
    restart: always
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment: 
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  redis:
    image: redis
  static:
    build:
      context: ./static
      dockerfile: Dockerfile
